Web/FerreTodoElArabito.Web/Models/ErrorViewModel.cs
namespace FerreTodoElArabito.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }



        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/FerreTodoElArabito.Web/Controllers/AdministracionController.cs
using Microsoft.AspNetCore.Mvc;

namespace FerreTodoElArabito.Web.Controllers
{
    public class AdministracionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/FerreTodoElArabito.Web/Controllers/ClientesController.cs
using FT.Lib.Data.Dal;
using FT.Lib.Data.Models.Filtro;
using Microsoft.AspNetCore.Mvc;

namespace FerreTodoElArabito.Web.Controllers
{
    public class ClientesController : Controller
    {
        [HttpGet]
        [Route("/Agregar")]
        public async Task<IActionResult> Agregar(Guid? token)
        {
            if (token.HasValue)
            {

            }
            return View();
        }

        [HttpGet]
        [Route("/Clientes")]
        public async Task<IActionResult> Clientes()
        {
            using var instance = new FerreTodoDal();
            ViewBag.Filtro = new FiltroClientes();
            var model = await instance.ObtenerClientes();
            return View(model);
        }

        [HttpPost]
        [Route("/Clientes/Obtener")]
        public IActionResult Listar([FromBody] FiltroClientes data)
        {
            using var instancia = new FerreTodoDal();
            ViewBag.Filtro = new FiltroClientes();
            //var resultado

            return Json(new { Mensaje = "EL MENSAJE ES EXITOSO", Status = "OK" });
        }
    }
}

Web/FerreTodoElArabito.Web/Controllers/CuentasPorCobrarController.cs
using FT.Lib.Data.Dal;
using FT.Lib.Data.Models.Filtro;
using FT.Lib.Data.Models.CuentasPorCobrar;
using Microsoft.AspNetCore.Mvc;

namespace FerreTodoElArabito.Web.Controllers
{
    public class CuentasPorCobrarController : Controller
    {
        [HttpGet]
        [Route("/Agregar")]
        public async Task<IActionResult> Agregar(Guid? token)
        {
            if (token.HasValue)
            {

            }
            return View();
        }

        [HttpGet]
        [Route("/CuentasPorCobrar")]
        public async Task<IActionResult> CuentasPorCobrar()
        {
            using var instance = new FerreTodoDal();
            ViewBag.Filtro = new FiltroCuentasPorCobrar();
            var model = await instance.ObtenerCuentasPorCobrar();
            return View(model);
        }

        [HttpPost]
        [Route("/CuentasPorCobrar/Obtener")]
        public IActionResult Listar([FromBody] FiltroCuentasPorCobrar data)
        {
            using var instancia = new FerreTodoDal();
            ViewBag.Filtro = new FiltroCuentasPorCobrar();
            //var resultado

            return Json(new { Mensaje = "EL MENSAJE ES EXITOSO", Status = "OK" });
        }
    }
}

Web/FerreTodoElArabito.Web/Controllers/CuentasPorPagarController.cs
using FT.Lib.Data.Dal;
using FT.Lib.Data.Models.Filtro;
using FT.Lib.Data.Models.CuentasPorPagar;
using Microsoft.AspNetCore.Mvc;


namespace FerreTodoElArabito.Web.Controllers
{
    public class CuentasPorPagarController : Controller
    {
        [HttpGet]
        [Route("/Agregar")]
        public async Task<IActionResult> Agregar(Guid? token)
        {
            if (token.HasValue)
            {

            }
            return View();
        }

        [HttpGet]
        [Route("/CuentasPorPagar")]
        public async Task<IActionResult> CuentasPorPagar()
        {
            using var instance = new FerreTodoDal();
            ViewBag.Filtro = new FiltroCuentasPorPagar();
            var model = await instance.ObtenerCuentasPorPagar();
            return View(model);
        }

        [HttpPost]
        [Route("/CuentasPorPagar/Obtener")]
        public IActionResult Listar([FromBody] FiltroCuentasPorPagar data)
        {
            using var instancia = new FerreTodoDal();
            ViewBag.Filtro = new FiltroCuentasPorPagar();
            //var resultado

            return Json(new { Mensaje = "EL MENSAJE ES EXITOSO", Status = "OK" });
        }
    }
}

Web/FerreTodoElArabito.Web/Controllers/HomeController.cs
using FerreTodoElArabito.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FerreTodoElArabito.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger; 
        }

        public IActionResult Index()
        {
            string prueba = "";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/FerreTodoElArabito.Web/Controllers/InventarioController.cs
using FT.Lib.Data.Dal;
using FT.Lib.Data.Models.Filtro;
using FT.Lib.Data.Models.Inventario;
using Microsoft.AspNetCore.Mvc;

namespace FerreTodoElArabito.Web.Controllers
{
    public class InventarioController : Controller
    {
        [HttpGet]
        [Route("/Inventario/Agregar")]
        public async Task<IActionResult> AgregarProducto(Guid? token)
        {
            using var instancia = new FerreTodoDal();
            if (token.HasValue)
            {
                var model = await instancia.ObtenerProducto(token.Value);
                ViewBag.EsAgregar = false;
                return PartialView(model);
            }

            ViewBag.EsAgregar = true;
            return View();
        }

        [HttpGet]
        [Route("/Inventario")]
        public async Task<IActionResult> Inventario()
        {
            using var instance = new FerreTodoDal();
            ViewBag.Filtro = new FiltroInventario();
            var model = await instance.ObtenerInventario(new FiltroInventario());
            return View();
        }

        [HttpPost]
        [Route("/Inventario/Obtener")]
        public async Task<IActionResult> Listar([FromBody] FiltroInventario data)
        {
            using var instancia = new FerreTodoDal();
            ViewBag.Filtro = new FiltroInventario();
            //var resultado

            return Json(new { Mensaje = "EL MENSAJE ES EXITOSO", Status = "OK" });
        }
    }
}

Web/FerreTodoElArabito.Web/Controllers/ProveedoresController.cs
using FT.Lib.Data.Dal;
using FT.Lib.Data.Models.Filtro;
using Microsoft.AspNetCore.Mvc;

namespace FerreTodoElArabito.Web.Controllers
{
    public class ProveedoresController : Controller
    {
        [HttpGet]
        [Route("/Agregar")]
        public async Task<IActionResult> Agregar(Guid? token)
        {
            if (token.HasValue)
            {

            }
            return View();
        }

        [HttpGet]
        [Route("/Proveedores")]
        public async Task<IActionResult> Proveedores()
        {
            using var instance = new FerreTodoDal();
            ViewBag.Filtro = new FiltroProveedores();
            var model = await instance.ObtenerProveedores();
            return View(model);
        }

        [HttpPost]
        [Route("/Proveedores/Obtener")]
        public IActionResult Listar([FromBody] FiltroProveedores data)
        {
            using var instancia = new FerreTodoDal();
            ViewBag.Filtro = new FiltroProveedores();
            //var resultado

            return Json(new { Mensaje = "EL MENSAJE ES EXITOSO", Status = "OK" });
        }
    }
}

Web/FerreTodoElArabito.Web/Controllers/SistemaController.cs
using Microsoft.AspNetCore.Mvc;

namespace FerreTodoElArabito.Web.Controllers
{
    public class SistemaController : Controller
    {
        public IActionResult Login(Guid token)
        {
            return View();
        }
        
        public IActionResult Registrar()
        {
            return View();
        }
        
        public IActionResult Recuperar()
        {
            return View();
        }

    }
}

Web/FerreTodoElArabito.Web/Controllers/UsuariosController.cs
using FT.Lib.Data.Dal;
using FT.Lib.Data.Models.Filtro;
using Microsoft.AspNetCore.Mvc;

namespace FerreTodoElArabito.Web.Controllers
{
    public class UsuariosController : Controller
    {

        [HttpGet]
        [Route("/Usuarios")]
        public IActionResult Usuarios()
        {
            using var instance = new FerreTodoDal();
            ViewBag.Filtro = new FiltroUsuario();
            //var model = await instance.ObtenerInventario(new FiltroInventario());
            return View();
        }
    }
}

Web/FerreTodoElArabito.Web/Views/Clientes/Clientes.cshtml
@using FT.Lib.Data.Models.Clientes
@model PagedList.PagedList<ElementoInvModel>
@{
    var filtro = ViewBag.Filtro as FT.Lib.Data.Models.Filtro.FiltroClientes;
}

<body>
    <div class="card">
        <div class="card-header">
            <h3><strong>Buscar Producto</strong></h3>
        </div>
        @await Html.PartialAsync("_FiltroClientes",filtro)
    </div>

    @await Html.PartialAsync("_Listar",Model)
</body>
@* </html> *@

Web/FerreTodoElArabito.Web/Views/Clientes/_FiltroClientes.cshtml
@model FT.Lib.Data.Models.Filtro.FiltroClientes
<div class="card-body" style="margin-top:10px;">
    @using (Html.BeginForm("Obtener", "Clientes", FormMethod.Post))
    {
        <div class="col-12" style="margin-top:10px;">
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        @Html.LabelFor(t => t.Nombre, new { @class = "text-label" })
                        <div class="input-group input-group-merge">
                            @Html.TextBoxFor(t => t.Nombre, new { @class = "form-control form-control-prepended" })
                            @Html.ValidationMessageFor(t => t.Nombre)
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        @Html.LabelFor(t => t.Tipo, new { @class = "text-label" })
                        <div class="input-group input-group-merge">
                            @Html.TextBoxFor(t => t.Tipo, new { @class = "form-control form-control-prepended" })
                            @Html.ValidationMessageFor(t => t.Tipo)
                        </div>
                    </div>
                </div>
                <div class="col-12" style="margin-top:15px;text-align: right;">
                    <button type="submit" data-enviogenerico class="btn btn-primary">Buscar Productos</button>
                </div>
            </div>
        </div>
    }

@*     <div class="col-12" style="margin-top:15px;text-align: right;">
        <button type="submit" data-enviogenerico class="btn btn-primary">Buscar Productos</button>
    </div> *@
</div>

Web/FerreTodoElArabito.Web/Views/Clientes/_Listar.cshtml
@using FT.Lib.Data.Models.Clientes
@model PagedList.PagedList<ElementoInvModel>

<div class="card">
    <div class="card-header"><h3><strong>Resultados</strong></h3></div>
    <div class="card-body">
        @* <div class="table col-12"> *@
        <table class="table col-12">
            <thead>
                <tr>
                    <th>Codigo</th>
                    <th>Nombre</th>
                    <th>Telefono</th>
                </tr>
            </thead>
            <tbody data-resultados>
                <tr>
                    <td>1232452</td>
                    <td>Distribuidora shalala</td>
                    <td>22562222</td>
                </tr>
                <tr>
                    <td>1232452</td>
                    <td>Distribuidora shalala</td>
                    <td>22562222</td>
                </tr>
                <tr>
                    <td>1232452</td>
                    <td>Distribuidora shalala</td>
                    <td>22562222</td>
                </tr>
                <tr>
                    <td>1232452</td>
                    <td>Distribuidora shalala</td>
                    <td>22562222</td>
                </tr>
            </tbody>
        </table>

    </div>
</div>

Web/FerreTodoElArabito.Web/Views/CuentasPorCobrar/CuentasPorCobrar.cshtml
@using FT.Lib.Data.Models.CuentasPorCobrar
@model PagedList.PagedList<ElementoInvModel>
@{
    var filtro = ViewBag.Filtro as FT.Lib.Data.Models.Filtro.FiltroCuentasPorCobrar;
}

<body>
    <div class="card">
        <div class="card-header">
            <h3><strong>Buscar Producto</strong></h3>
        </div>
        @await Html.PartialAsync("_FiltroCuentasPorCobrar", filtro)
    </div>

    @await Html.PartialAsync("_Listar", Model)
</body>
@* </html> *@

Web/FerreTodoElArabito.Web/Views/CuentasPorCobrar/_FiltroCuentasPorCobrar.cshtml
@model FT.Lib.Data.Models.Filtro.FiltroCuentasPorCobrar
<div class="card-body" style="margin-top:10px;">
    @using (Html.BeginForm("Obtener", "CuentasPorCobrar", FormMethod.Post))
    {
        <div class="col-12" style="margin-top:10px;">
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        @Html.LabelFor(t => t.Nombre, new { @class = "text-label" })
                        <div class="input-group input-group-merge">
                            @Html.TextBoxFor(t => t.Nombre, new { @class = "form-control form-control-prepended" })
                            @Html.ValidationMessageFor(t => t.Nombre)
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        @Html.LabelFor(t => t.Tipo, new { @class = "text-label" })
                        <div class="input-group input-group-merge">
                            @Html.TextBoxFor(t => t.Tipo, new { @class = "form-control form-control-prepended" })
                            @Html.ValidationMessageFor(t => t.Tipo)
                        </div>
                    </div>
                </div>
                <div class="col-12" style="margin-top:15px;text-align: right;">
                    <button type="submit" data-enviogenerico class="btn btn-primary">Buscar cuentas por cobrar</button>
                </div>
            </div>
        </div>
    }

    @*     <div class="col-12" style="margin-top:15px;text-align: right;">
    <button type="submit" data-enviogenerico class="btn btn-primary">Buscar Productos</button>
    </div> *@
</div>

Web/FerreTodoElArabito.Web/Views/CuentasPorCobrar/_Listar.cshtml
@using FT.Lib.Data.Models.CuentasPorCobrar
@model PagedList.PagedList<ElementoInvModel>

<div class="card">
    <div class="card-header"><h3><strong>Resultados</strong></h3></div>
    <div class="card-body">
        @* <div class="table col-12"> *@
        <table class="table col-12">
            <thead>
                <tr>
                    <th>Número de documento</th>
                    <th>Fecha de emisión </th>
                    <th>Monto del documento</th>
                    <th>Emisor de la factura</th>
                    <th>Receptor de la factura</th>
                    <th>Tipo de documento</th>
                </tr>
            </thead>
            <tbody data-resultados>
                <tr>
                    <td>1177508487</td>
                    <td>22/03/24</td>
                    <td>100.000</td>
                    <td>Ferreteria por mayor</td>
                    <td>Ferretodo el Arabito</td>
                    <td>Recibo</td>
                </tr>
                <tr>
                    <td>1177508487</td>
                    <td>22/03/24</td>
                    <td>100.000</td>
                    <td>Ferreteria por mayor</td>
                    <td>Ferretodo el Arabito</td>
                    <td>Recibo</td>
                </tr>
            </tbody>
        </table>

    </div>
</div>

Web/FerreTodoElArabito.Web/Views/CuentasPorPagar/CuentasPorPagar.cshtml
@using FT.Lib.Data.Models.CuentasPorPagar
@model PagedList.PagedList<ElementoInvModel>
@{
    var filtro = ViewBag.Filtro as FT.Lib.Data.Models.Filtro.FiltroCuentasPorPagar;
}

<body>
    <div class="card">
        <div class="card-header">
            <h3><strong>Buscar Producto</strong></h3>
        </div>
        @await Html.PartialAsync("_FiltroCuentasPorPagar",filtro)
    </div>

    @await Html.PartialAsync("_Listar",Model)
</body>
@* </html> *@

Web/FerreTodoElArabito.Web/Views/CuentasPorPagar/_FiltroCuentasPorPagar.cshtml
@model FT.Lib.Data.Models.Filtro.FiltroCuentasPorPagar
<div class="card-body" style="margin-top:10px;">
    @using (Html.BeginForm("Obtener", "CuentasPorPagar", FormMethod.Post))
    {
        <div class="col-12" style="margin-top:10px;">
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        @Html.LabelFor(t => t.Nombre, new { @class = "text-label" })
                        <div class="input-group input-group-merge">
                            @Html.TextBoxFor(t => t.Nombre, new { @class = "form-control form-control-prepended" })
                            @Html.ValidationMessageFor(t => t.Nombre)
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        @Html.LabelFor(t => t.Tipo, new { @class = "text-label" })
                        <div class="input-group input-group-merge">
                            @Html.TextBoxFor(t => t.Tipo, new { @class = "form-control form-control-prepended" })
                            @Html.ValidationMessageFor(t => t.Tipo)
                        </div>
                    </div>
                </div>
                <div class="col-12" style="margin-top:15px;text-align: right;">
                    <button type="submit" data-enviogenerico class="btn btn-primary">Buscar Productos</button>
                </div>
            </div>
        </div>
    }

@*     <div class="col-12" style="margin-top:15px;text-align: right;">
        <button type="submit" data-enviogenerico class="btn btn-primary">Buscar Productos</button>
    </div> *@
</div>

Web/FerreTodoElArabito.Web/Views/Inventario/AgregarProducto.cshtml
@model FT.Lib.Data.Models.Inventario.ProductoModel

@{
    bool? esAgregar = ViewBag.EsAgregar as bool?;
}

<div class="card">
    <div class="card-header">
        <h3><strong>@(esAgregar == true ? "Agregar Producto" : "Modificar Producto")</strong></h3>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Obtener", "Inventario", FormMethod.Post))
        {
            <div class="col-12">
                <div class="row">
                    <div class="col-6 mt-2 mb-2">
                        <div class="form-group">
                            @Html.LabelFor(t => t.Nombre, new { @class = "text-label" })
                            <div class="input-group input-group-merge">
                                @Html.TextBoxFor(t => t.Nombre, new { @class = "form-control form-control-prepended" })
                                @Html.ValidationMessageFor(t => t.Nombre)
                            </div>
                        </div>
                    </div>
                    <div class="col-6 mt-2 mb-2">
                        <div class="form-group">
                            @Html.LabelFor(t => t.Codigo, new { @class = "text-label" })
                            <div class="input-group input-group-merge">
                                @Html.TextBoxFor(t => t.Codigo, new { @class = "form-control form-control-prepended" })
                                @Html.ValidationMessageFor(t => t.Codigo)
                            </div>
                        </div>
                    </div>
                    <div class="col-12 mt-2 mb-2">
                        <div class="form-group">
                            @Html.LabelFor(t => t.Descripcion, new { @class = "text-label" })
                            <div class="input-group input-group-merge">
                                @Html.TextAreaFor(t => t.Descripcion, new { @class = "form-control form-control-prepended" })
                                @Html.ValidationMessageFor(t => t.Descripcion)
                            </div>
                        </div>
                    </div>
                    <div class="col-6 mt-2 mb-2">
                        <div class="form-group">
                            @Html.LabelFor(t => t.Cantidad, new { @class = "text-label" })
                            <div class="input-group input-group-merge">
                                @Html.TextBoxFor(t => t.Cantidad, new { @class = "form-control form-control-prepended" })
                                @Html.ValidationMessageFor(t => t.Cantidad)
                            </div>
                        </div>
                    </div>
                    <div class="col-6 mt-2 mb-2">
                        <div class="form-group">
                            @Html.LabelFor(t => t.Modelo, new { @class = "text-label" })
                            <div class="input-group input-group-merge">
                                @Html.TextBoxFor(t => t.Modelo, new { @class = "form-control form-control-prepended" })
                                @Html.ValidationMessageFor(t => t.Modelo)
                            </div>
                        </div>
                    </div>
                    <div class="col-6 mt-2 mb-2">
                        <div class="form-group">
                            @Html.LabelFor(t => t.TipoVentaId, new { @class = "text-label" })
                            <div class="input-group input-group-merge">
                                @Html.TextBoxFor(t => t.TipoVentaId, new { @class = "form-control form-control-prepended" })
                                @Html.ValidationMessageFor(t => t.TipoVentaId)
                            </div>
                        </div>
                    </div>
                    <div class="col-6 mt-2 mb-2">
                        <div class="form-group">
                            @Html.LabelFor(t => t.Serie, new { @class = "text-label" })
                            <div class="input-group input-group-merge">
                                @Html.TextBoxFor(t => t.Serie, new { @class = "form-control form-control-prepended" })
                                @Html.ValidationMessageFor(t => t.Serie)
                            </div>
                        </div>
                    </div>
                    <div class="col-12" style="margin-top:15px;text-align: right;">
                        <button type="submit" data-enviogenerico class="btn btn-primary">Guardar</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Web/FerreTodoElArabito.Web/Views/Inventario/_FiltroInventario.cshtml
@model FT.Lib.Data.Models.Filtro.FiltroInventario
<div class="card-body" style="margin-top:10px;">
    @using (Html.BeginForm("Obtener", "Inventario", FormMethod.Post))
    {
        <div class="col-12" style="margin-top:10px;">
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        @Html.LabelFor(t => t.Nombre, new { @class = "text-label" })
                        <div class="input-group input-group-merge">
                            @Html.TextBoxFor(t => t.Nombre, new { @class = "form-control form-control-prepended" })
                            @Html.ValidationMessageFor(t => t.Nombre)
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        @Html.LabelFor(t => t.Codigo, new { @class = "text-label" })
                        <div class="input-group input-group-merge">
                            @Html.TextBoxFor(t => t.Codigo, new { @class = "form-control form-control-prepended" })
                            @Html.ValidationMessageFor(t => t.Codigo)
                        </div>
                    </div>
                </div>
                <div class="col-12" style="margin-top:15px;text-align: right;">
                    <button type="submit" data-busquedagenerico class="btn btn-primary">Buscar Productos</button>
                    <button type="submit" class="btn btn-success">Agregar Productos</button>
                </div>
            </div>
        </div>
    }

@*     <div class="col-12" style="margin-top:15px;text-align: right;">
        <button type="submit" data-enviogenerico class="btn btn-primary">Buscar Productos</button>
    </div> *@
</div>

Web/FerreTodoElArabito.Web/Views/Proveedores/_FiltroProveedores.cshtml
@model FT.Lib.Data.Models.Filtro.FiltroProveedores
<div class="card-body" style="margin-top:10px;">
    @using (Html.BeginForm("Obtener", "Proveedores", FormMethod.Post))
    {
        <div class="col-12" style="margin-top:10px;">
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        @Html.LabelFor(t => t.Nombre, new { @class = "text-label" })
                        <div class="input-group input-group-merge">
                            @Html.TextBoxFor(t => t.Nombre, new { @class = "form-control form-control-prepended" })
                            @Html.ValidationMessageFor(t => t.Nombre)
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        @Html.LabelFor(t => t.Tipo, new { @class = "text-label" })
                        <div class="input-group input-group-merge">
                            @Html.TextBoxFor(t => t.Tipo, new { @class = "form-control form-control-prepended" })
                            @Html.ValidationMessageFor(t => t.Tipo)
                        </div>
                    </div>
                </div>
                <div class="col-12" style="margin-top:15px;text-align: right;">
                    <button type="submit" data-enviogenerico class="btn btn-primary">Buscar Productos</button>
                </div>
            </div>
        </div>
    }

@*     <div class="col-12" style="margin-top:15px;text-align: right;">
        <button type="submit" data-enviogenerico class="btn btn-primary">Buscar Productos</button>
    </div> *@
</div>

Web/FerreTodoElArabito.Web/Views/Sistema/Login.cshtml
@model FT.Lib.Data.Models.LogIn.LogInModel

@{
    Layout = "/Views/Shared/_LayoutLogIn.cshtml";
    ViewData["Title"] = "Ingresar";
}


<div class="container col-12">

    <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
                    <img src="/assets/img/NewIcono.png.png" style="width:500px;margin-bottom: -30px;margin-left: -20px;">

                    <div class="d-flex justify-content-center py-4">
                        <div>
                            <a class="logo d-flex align-items-center w-auto">
                    @* <img src="/assets/img/NewIcono.png.png" style="width:105px;"> *@

                                <span class="d-none d-lg-block">¡Bienvenido!</span>
                            </a>
                        </div> 
                    </div> 

                   @*  <div class="col-12 mb-3">
                        <div class="row">
                            <div class="col-6 mr-2">
                                <img src="/assets/img/just-iconE.png" style="width:105px;">
                            </div>
                            <div class="col-6">
                                <a class="logo d-flex align-items-center w-auto">
                                    <span class="d-none d-lg-block">¡Bienvenido!</span>
                                </a>
                            </div>
                        </div>

                    </div> *@

                    <div class="card mb-3">

                        <div class="card-body">

                            <div class="pt-4 pb-2">
                                <h5 class="card-title text-center pb-0 fs-4">Credenciales del sistema</h5>
                                <p class="text-center small">Ingrese su usuario y contraseña para utilizar la herramienta</p>
                            </div>
                            @using (Html.BeginForm("Ingresar", "Sistema", FormMethod.Post))
                            {

                                @* <form class="row g-3 needs-validation" novalidate> *@

                                <div class="col-12">
                                    @Html.LabelFor(t => t.Username, "Usuario:", new { @class = "form-label" })
                                    <div class="input-group has-validation">
                                        <span class="input-group-text"><i class="bi bi-person"></i></span>
                                        @Html.TextBoxFor(t => t.Username, new { @class = "form-control", placeholder = "habarca23" })
                                        @Html.ValidationMessageFor(t => t.Username)
                                    </div>
                                </div>

                                <div class="col-12 mt-2">
                                    @Html.LabelFor(t => t.Password, "Contraseña:", new { @class = "form-label password"})
                                    @Html.TextBoxFor(t => t.Password, new { @class = "form-control", type = "password" })
                                    @Html.ValidationMessageFor(t => t.Password)
                                </div>

                                <div class="col-12 mt-2">
                                    <div class="form-check">
                                        @Html.LabelFor(t => t.Recordar, "Recordar:", new { @class = "form-check-label", @value = "true" })
                                        @Html.CheckBoxFor(t => t.Recordar, new { @class = "form-check-input" })
                                    </div>
                                </div>

@*                                 <div class="col-12">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe">
                                        <label class="form-check-label" for="rememberMe">Recordar</label>
                                    </div>
                                </div> *@
                                <div class="col-12 mt-3">
                                    <button class="btn btn-primary w-100" type="submit">Ingresar</button>
                                </div>
                                <div class="col-12 mt-2">
                                    <p class="small mb-0">Aun no tienes cuenta? <a href="pages-register.html">Crear una cuenta</a></p>
                                </div>
                                @* </form> *@
                            }

                        </div>
                    </div>

                </div>
            </div>
        </div>

    </section>

</div>